"""did some changes to models.py

Revision ID: c40a1802f9d3
Revises: d34bf7463017
Create Date: 2025-12-03 11:40:30.713871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40a1802f9d3'
down_revision: Union[str, None] = 'd34bf7463017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfits', sa.Column('name', sa.Text(), nullable=False))
    op.drop_column('outfits', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfits', sa.Column('title', sa.TEXT(), nullable=False))
    op.drop_column('outfits', 'name')
    # ### end Alembic commands ###
